name: telsavideo
description: Decentralized video sharing platform like tiktok.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ffi: ^1.1.2
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7
  google_mobile_ads: ^0.13.4
  #firebase_analytics: ^8.3.2
  #firebase_auth: ^1.2.0
  flutter_bloc: ^7.0.1
  json_annotation: ^4.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  oauth2: ^2.0.0
  font_awesome_flutter: ^9.0.0
  dio: ^4.0.0
  url_launcher: ^6.0.6
  platform: ^3.0.2
  path_provider: ^2.0.2
  path_provider_platform_interface: ^2.0.0
  shared_preferences: ^2.0.6
  modal_bottom_sheet: ^2.0.0
  #screen: ^0.0.5
  html: ^0.15.0
  uni_links: ^0.5.1
  flutter_custom_tabs: ^0.7.0
  modal_progress_hud_alt: ^1.0.0
  quiver: ^3.0.0
  video_player: ^2.2.2
  camera: ^0.9.2+2
  in_app_purchase: ^1.0.8
  package_info: ^2.0.2
  share: ^2.0.4
  #flutter_android_pip: ^0.0.2
  flutter_local_notifications: ^6.0.0
  permission_handler: ^8.0.1
  open_file: ^3.0.1
  #flutter_downloader: ^1.7.0
  cached_network_image: ^3.1.0
  carousel_slider: ^3.0.0
  simple_moment: ^1.0.6
  cupertino_icons: ^1.0.2
  flutter_html: ^2.1.0
  chewie: ^1.2.0
  #flutter_ffmpeg: ^0.4.0
  in_app_update: ^2.0.0
  #video_launcher: 
  #   git:
  #      url: git@github.com:TelsaCoin/flutter_video_launcher.git
  #      ref: master
  flutter_svg: ^0.22.0
  #http: ^0.13.3
  provider: ^5.0.0
  avatar_glow: any
  #getflutter: ^1.1.3
  getwidget: ^2.0.4
  #money_formatter: ^0.0.3
  #fijkplayer:
  #  git:
  #    url: https://github.com/befovy/fijkplayer.git
  #    ref: develop
  dio_cookie_manager: ^2.0.0
  marquee_widget: ^1.2.0
  toast: ^0.1.5
  fluttertoast: ^8.0.3
  #upgrader: ^3.5.1
  carousel_pro_nullsafety: ^1.0.2
  flutter_switch: ^0.3.2
  flutter_spinkit: ^5.1.0
  intl_phone_number_input: ^0.7.0+2
  flutter_inappwebview: ^5.3.2
  flutter_signin_button: ^2.0.0
  form_field_validator: ^1.0.1
  google_fonts: ^2.0.0
  #google_sign_in: ^5.1.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  lottie: ^1.0.1
  expandable: ^5.0.1
  sign_in_with_apple: ^3.0.0
  page_transition: ^2.0.2
  flutter_form_builder: ^6.0.1
  #https://github.com/fluttercommunity/plus_plugins
  #device_info_plus: ^2.1.0

dev_dependencies:
  stack_trace: ^1.10.0
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  flutter_launcher_icons: ^0.9.0
  flutter_ume: ^0.2.1  # null-safety 版本: ^0.2.1
  flutter_ume_kit_ui: ^0.2.1  # null-safety 版本: ^0.2.1
  flutter_ume_kit_device: ^0.2.1  # null-safety 版本: ^0.2.1
  flutter_ume_kit_perf: ^0.2.1  # null-safety 版本: ^0.2.1
  flutter_ume_kit_show_code: ^0.2.1  # null-safety 版本: ^0.2.1
  flutter_ume_kit_console: ^0.2.1  # null-safety 版本: ^0.2.1
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


flutter_icons:
  android: true
  ios: true
  image_path: "assets/dtok.png"
  adaptive_icon_background: "assets/appbackground.png" # only available for Android 8.0 devices and above
  #adaptive_icon_foreground: "assets/appbackground.png" # only available for Android 8.0 devices and above

module:
  androidX: true


# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/slider/
    - assets/dance/
    - assets/laugh/
    - assets/food/
    - assets/user_profile/
    - assets/user.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DouyinIcons
      fonts:
        - asset: assets/fonts/TikTokIcons.ttf
        # - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        # - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        #   weight: 600
        # - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        #   weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
